captainVersion: 4
services:
    '$$cap_appname':
        image: realtradam/openrct2-docker:$$cap_version
        environment:
            RCT2MAP: '$$cap_rct2_map_path'
        volumes:
            - '$$cap_appname-data:/home/openrct2/.config/OpenRCT2'
            - '$$cap_rct2_data_mount'
            #- '/var/lib/docker/volumes/captain--next-data/_data/data/admin/files/Documents/rct2/openrct2/Scenarios/RCT2:/home/openrct2/Parks'
        ports:
            - 11753:11753
        caproverExtra:
          notExposeAsWebApp: 'true'
caproverOneClickApp:
    variables:
        - id: '$$cap_version'
          label: OpenRCT2 Version
          defaultValue: '0.4.11'
          description: Check out the Docker page for the valid tags https://hub.docker.com/r/realtradam/openrct2-cli/tags
        - id: '$$cap_rct2_map_path'
          label: OpenRCT2 Map Path
          defaultValue: '/home/openrct2/mounted_data/openrct2/Scenarios/RCT2/Bumbly Bazaar.SC6'
          description: What map or save you want to load. Note that this docker file does not contain any maps so this default value wont work unless you provide the map.
        - id: '$$cap_rct2_data_mount'
          label: OpenRCT2 Data Mount
          defaultValue: '/var/lib/docker/volumes/captain--next-data/_data/data/admin/files/Documents/rct2:/home/openrct2/mounted_data'
          description: What and where to mount RCT data. I set ip all my data on a next cloud instance and then mount it from there hence the default.
    instructions:
        start: |-
            Server for hosting OpenRCT2 games.
        end: |-
            OpenRCT2 has been successfully deployed!
    displayName: OpenRCT2
    isOfficial: false
    description: Open source reimplementation of OpenRCT2, hosts multiplayer games.
    documentation: See https://github.com/OpenRCT2/openrct2-docker
